apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-local-pv-{{ .Release.Name }}
spec:
  capacity:
    storage: {{ .Values.mongodb.persistence.size | default "1Gi" }}
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-sc
  hostPath:
    path: /mnt/mongodb-data
